spring.thymeleaf.cache: false
file_server:
  ali_oss:
    endPoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIRbs0HTznrtuI
    accessKeySecret: psbzpaxib4MADfHOvULqewGe6bFmgj
    bucketName: lalakapic
    folder: image/
    accessUrl: http://lalakapic.oss-cn-shenzhen.aliyuncs.com
server:
  port: 8081