spring.thymeleaf.cache: false
file_server:
  ali_oss:
    endPoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAuI
    accessKeySecret: psbzpbFmgj
    bucketName: pic
    folder: image/
    accessUrl: http://pic.oss-cn-shenzhen.aliyuncs.com