spring.thymeleaf.cache: false
file_server:
  ali_oss:
    endPoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIRbs0HTdfdsafznrtuI
    accessKeySecret: fdasfasfsa
    bucketName: lalakapic
    folder: image/
    accessUrl: http://ddd.oss-cn-shenzhen.aliyuncs.com
server:
  port: 8081