spring.thymeleaf.cache: false
file_server:
  ali_oss:
    endPoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: dd
    accessKeySecret: psbzpaxi
    bucketName: lalakapic
    folder: image/
    accessUrl: http://dd.oss-cn-shenzhen.aliyuncs.com
server:
  port: 8081